# Generated by Django 2.2.12 on 2020-04-04 13:11

from django.db import migrations, models
import rest_apis.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50, unique=True, validators=[rest_apis.models.is_email])),
                ('password', models.CharField(max_length=20)),
                ('confirmpass', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'register',
            },
        ),
    ]
