# Generated by Django 2.2.12 on 2020-04-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0002_brand_category_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
