# Generated by Django 2.2.12 on 2020-04-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0003_auto_20200407_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
    ]
