# Generated by Django 2.2.12 on 2020-04-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0004_auto_20200408_0541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_path', models.TextField()),
                ('img_pid', models.IntegerField()),
                ('img_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'images',
            },
        ),
    ]
