# Generated by Django 2.2.12 on 2020-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=29)),
                ('brand_time', models.DateTimeField(blank=True)),
            ],
            options={
                'managed': False,
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=29)),
                ('cat_time', models.DateTimeField(blank=True)),
            ],
            options={
                'managed': False,
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_caid', models.IntegerField(blank=True, null=True)),
                ('p_brid', models.IntegerField(blank=True, null=True)),
                ('p_mrp', models.IntegerField(blank=True, null=True)),
                ('p_dis', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('p_descrip', models.TextField(blank=True, null=True)),
                ('p_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'product',
            },
        ),
    ]
